name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
      
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@v3.34  # Updated to the correct version
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: MAInformatico
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: true
          config_octicon: true
          config_timezone: America/Chicago
          config_twemoji: true
          plugin_languages: true
          plugin_languages_ignored: hack
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: true
          plugin_languages_limit: 8
          plugin_languages_other: true
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
